// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOY_H543XfiVs6FIq3Qpu4QqvqzmOinog',
    appId: '1:141844275662:web:300556c81930542d118b9f',
    messagingSenderId: '141844275662',
    projectId: 'eduhub-102',
    authDomain: 'eduhub-102.firebaseapp.com',
    storageBucket: 'eduhub-102.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYdzKAG6NkbEHa8IgWNChwNkHSPy9xYGE',
    appId: '1:141844275662:android:3677052b3ec5ab1c118b9f',
    messagingSenderId: '141844275662',
    projectId: 'eduhub-102',
    storageBucket: 'eduhub-102.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgcqrQYp6aCuCSofvFXnp0ke9zoQg-EN4',
    appId: '1:141844275662:ios:ae44dc6c63f6abb8118b9f',
    messagingSenderId: '141844275662',
    projectId: 'eduhub-102',
    storageBucket: 'eduhub-102.firebasestorage.app',
    iosBundleId: 'com.example.eduhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgcqrQYp6aCuCSofvFXnp0ke9zoQg-EN4',
    appId: '1:141844275662:ios:ae44dc6c63f6abb8118b9f',
    messagingSenderId: '141844275662',
    projectId: 'eduhub-102',
    storageBucket: 'eduhub-102.firebasestorage.app',
    iosBundleId: 'com.example.eduhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOY_H543XfiVs6FIq3Qpu4QqvqzmOinog',
    appId: '1:141844275662:web:3fd218bf8acf8573118b9f',
    messagingSenderId: '141844275662',
    projectId: 'eduhub-102',
    authDomain: 'eduhub-102.firebaseapp.com',
    storageBucket: 'eduhub-102.firebasestorage.app',
  );
}
