class Localization {
  static final Map<String, Map<String, String>> _texts = {
    "English": {
      "home": "Home",
      "course": "Course",
      "class": "Class",
      "assignments": "Assignments",
      "profile": "Profile",
      "homeScreenTeacher": "Home Screen (Teacher)",
      "homeScreenStudent": "Home Screen (Student)",
      "coursePage": "Hello from course",
      "classesTeacher": "My Classes",
      "classesStudent": "Enrolled Classes",
      "assignmentsTeacher": "Assignments to Grade",
      "assignmentsStudent": "My Assignments",
      "firstName": "First Name",
      "lastName": "Last Name",
      "email": "Email",
      "role": "Role",
      "selectLanguage": "Select Language",
    },
    "Khmer": {
      "home": "ផ្ទះ",
      "course": "វគ្គសិក្សា",
      "class": "ថ្នាក់",
      "assignments": "ការងារផ្ញើ",
      "profile": "ប្រវត្តិរូប",
      "homeScreenTeacher": "ផ្ទះ (គ្រូ)",
      "homeScreenStudent": "ផ្ទះ (សិស្ស)",
      "coursePage": "សួស្ដីពីវគ្គសិក្សា",
      "classesTeacher": "ថ្នាក់របស់ខ្ញុំ",
      "classesStudent": "ថ្នាក់ដែលចុះឈ្មោះ",
      "assignmentsTeacher": "ការងារដើម្បីផ្ដល់ពិន្ទុ",
      "assignmentsStudent": "ការងាររបស់ខ្ញុំ",
      "firstName": "នាមខ្លួន",
      "lastName": "នាមត្រកូល",
      "email": "អ៊ីម៉ែល",
      "role": "តួនាទី",
      "selectLanguage": "ជ្រើសភាសា",
    },
    "Chinese": {
      "home": "主页",
      "course": "课程",
      "class": "班级",
      "assignments": "作业",
      "profile": "个人资料",
      "homeScreenTeacher": "主页（教师）",
      "homeScreenStudent": "主页（学生）",
      "coursePage": "你好，来自课程页面",
      "classesTeacher": "我的课程",
      "classesStudent": "已注册课程",
      "assignmentsTeacher": "待批作业",
      "assignmentsStudent": "我的作业",
      "firstName": "名字",
      "lastName": "姓氏",
      "email": "电子邮件",
      "role": "角色",
      "selectLanguage": "选择语言",
    },
    "Vietnamese": {
      "home": "Trang chủ",
      "course": "Khóa học",
      "class": "Lớp học",
      "assignments": "Bài tập",
      "profile": "Hồ sơ",
      "homeScreenTeacher": "Trang chủ (Giáo viên)",
      "homeScreenStudent": "Trang chủ (Học sinh)",
      "coursePage": "Xin chào từ trang khóa học",
      "classesTeacher": "Lớp của tôi",
      "classesStudent": "Lớp đã đăng ký",
      "assignmentsTeacher": "Bài tập cần chấm",
      "assignmentsStudent": "Bài tập của tôi",
      "firstName": "Tên",
      "lastName": "Họ",
      "email": "Email",
      "role": "Vai trò",
      "selectLanguage": "Chọn ngôn ngữ",
    }
  };

  static String text(String language, String key) {
    return _texts[language]?[key] ?? key;
  }
}
