class Localization {
  static final Map<String, Map<String, String>> _texts = {
    "English": {
      "home": "Home",
      "course": "Course",
      "class": "Class",
      "assignments": "Assignments",
      "profile": "Profile",
      "homeScreenTeacher": "Home Screen (Teacher)",
      "homeScreenStudent": "Home Screen (Student)",
      "coursePage": "Hello from course",
      "classesTeacher": "My Classes",
      "classesStudent": "Enrolled Classes",
      "assignmentsTeacher": "Assignments to Grade",
      "assignmentsStudent": "My Assignments",
      "firstName": "First Name",
      "lastName": "Last Name",
      "email": "Email",
      "role": "Role",
      "selectLanguage": "Select Language",
      "welcomeTitle": "Welcome to Eduhub",
      "welcomeDesc": "Boost your learning skills. Access homework, research materials, and teacher feedback all in one place.",
      "learnmore": "Learn More",
      "allsubjcts": "All Subjects",
      "searchsubjects": "Search subjects...",
      "seeMore": "See More",
      "seeLess": "See Less",
      "math": "Math",
      "science": "Science",
      "history": "History",
      "english": "English",
      "geography": "Geography",
      "physics": "Physics",
      "chemistry": "Chemistry",
      "biology": "Biology",
      "art": "Art",
      "music": "Music",
      "tech": "Tech",
      "sports": "Sports",
      "loading": "Loading...",
      "hubSubtitle": "Hub for Students & Teachers",
      "scholarshipOpportunities": "Scholarship Opportunities",
      "learningProgress": "Learning Progress",
      "latestNews": "Latest Education News",
      "Total Course Completion": "Total Course Completion",
      "seemore": "See More",
      "seeless": "See Less",
      "lessons": "Lessons",
      "Time": "Time",
      "Others": "Others",
      "schrolarshipOpportunities": "Scholarship Opportunities",
      "news&event": "News & Events",
      "LatesteducationNews": "Latest Education News",
      "accountDetails": "Account Details",
      "preferences": "Preferences",
      "Dark Mode": "Dark Mode",
      "Sign Out": "Sign Out",
    },
    "Khmer": {
      "home": "ផ្ទះ",
      "course": "វគ្គសិក្សា",
      "class": "ថ្នាក់",
      "assignments": "ការងារផ្ញើ",
      "profile": "ប្រវត្តិរូប",
      "homeScreenTeacher": "ផ្ទះ (គ្រូ)",
      "homeScreenStudent": "ផ្ទះ (សិស្ស)",
      "coursePage": "សួស្ដីពីវគ្គសិក្សា",
      "classesTeacher": "ថ្នាក់របស់ខ្ញុំ",
      "classesStudent": "ថ្នាក់ដែលចុះឈ្មោះ",
      "assignmentsTeacher": "ការងារដើម្បីផ្ដល់ពិន្ទុ",
      "assignmentsStudent": "ការងាររបស់ខ្ញុំ",
      "firstName": "នាមខ្លួន",
      "lastName": "នាមត្រកូល",
      "email": "អ៊ីម៉ែល",
      "role": "តួនាទី",
      "selectLanguage": "ជ្រើសភាសា",
      "welcomeTitle": "សូមស្វាគមន៍មកកាន់ Eduhub",
      "welcomeDesc": "បង្កើនជំនាញសិក្សារបស់អ្នក។ ចូលប្រើកិច្ចការផ្ទះ សម្ភារៈស្រាវជ្រាវ និងមតិកែលម្អរបស់គ្រូនៅកន្លែងតែមួយ។",
      "learnmore": "ស្វែងយល់បន្ថែម",
      "allsubjcts": "មុខវិជ្ជាទាំងអស់",
      "searchsubjects": "ស្វែងរកមុខវិជ្ជា...",
      "seeMore": "មើលបន្ថែម",
      "seeLess": "បង្ហាញតិច",
      "math": "គណិតវិទ្យា",
      "science": "វិទ្យាសាស្ត្រ",
      "history": "ប្រវត្តិវិទ្យា",
      "english": "ភាសាអង់គ្លេស",
      "geography": "ភូមិវិទ្យា",
      "physics": "រូបវិទ្យា",
      "chemistry": "គីមីវិទ្យា",
      "biology": "ជីវវិទ្យា",
      "art": "សិល្បៈ",
      "music": "តន្ត្រី",
      "tech": "បច្ចេកវិទ្យា",
      "sports": "កីឡា",
      "loading": "កំពុងផ្ទុក...",
      "hubSubtitle": "មជ្ឈមណ្ឌលសម្រាប់សិស្ស និងគ្រូ",
      "scholarshipOpportunities": "ឱកាសអាហារូបករណ៍",
      "learningProgress": "វឌ្ឍនភាពនៃការសិក្សា",
      "latestNews": "ព័ត៌មានអប់រំចុងក្រោយបង្អស់",
      "Total Course Completion": "ការសម្រេចបាននៃវគ្គសិក្សាសរុប",
      "seemore": "មើលបន្ថែម",
      "seeless": "បង្ហាញតិច",
      "Lessons": "មេរៀន",
      "Time": "ពេលវេលា",
      "Others": "ផ្សេងៗ",
      "schrolarshipOpportunities": "ឱកាសអាហារូបករណ៍",
      "news&event": "ព័ត៌មាន និងព្រឹត្តិការណ៍",
      "LatesteducationNews": "ព័ត៌មានអប់រំចុងក្រោយបង្អស់",
      "accountDetails": "ព័ត៌មានលម្អិតគណនី",
      "preferences": "ចំណង់ចំណូលចិត្ត",
      "Dark Mode": "របៀបងងឹត",
      "Sign Out": "ចាកចេញ",
    },
    "Chinese": {
      "home": "主页",
      "course": "课程",
      "class": "班级",
      "assignments": "作业",
      "profile": "个人资料",
      "homeScreenTeacher": "主页（教师）",
      "homeScreenStudent": "主页（学生）",
      "coursePage": "你好，来自课程页面",
      "classesTeacher": "我的课程",
      "classesStudent": "已注册课程",
      "assignmentsTeacher": "待批作业",
      "assignmentsStudent": "我的作业",
      "firstName": "名字",
      "lastName": "姓氏",
      "email": "电子邮件",
      "role": "角色",
      "selectLanguage": "选择语言",
      "welcomeTitle": "欢迎来到 Eduhub",
      "welcomeDesc": "提升您的学习技能。在一个地方访问作业、研究材料和教师反馈。",
      "learnmore": "了解更多",
      "allsubjcts": "所有科目",
      "searchsubjects": "搜索科目...",
      "seeMore": "查看更多",
      "seeLess": "收起",
      "math": "数学",
      "science": "科学",
      "history": "历史",
      "english": "英语",
      "geography": "地理",
      "physics": "物理",
      "chemistry": "化学",
      "biology": "生物",
      "art": "艺术",
      "music": "音乐",
      "tech": "技术",
      "sports": "体育",
      "loading": "加载中...",
      "hubSubtitle": "学生与教师中心",
      "scholarshipOpportunities": "奖学金机会",
      "learningProgress": "学习进度",
      "latestNews": "最新教育新闻",
      "Total Course Completion": "课程总完成度",
      "seemore": "查看更多",
      "seeless": "收起",
      "lessons": "课程",
      "Time": "时间",
      "Others": "其他",
      "schrolarshipOpportunities": "奖学金机会",
      "news&event": "新闻与活动",
      "LatesteducationNews": "最新教育新闻",
      "accountDetails": "账户详情",
      "preferences": "偏好设置",
      "Dark Mode": "深色模式",
      "Sign Out": "退出登录",
    },
    "Vietnamese": {
      "home": "Trang chủ",
      "course": "Khóa học",
      "class": "Lớp học",
      "assignments": "Bài tập",
      "profile": "Hồ sơ",
      "homeScreenTeacher": "Trang chủ (Giáo viên)",
      "homeScreenStudent": "Trang chủ (Học sinh)",
      "coursePage": "Xin chào từ trang khóa học",
      "classesTeacher": "Lớp của tôi",
      "classesStudent": "Lớp đã đăng ký",
      "assignmentsTeacher": "Bài tập cần chấm",
      "assignmentsStudent": "Bài tập của tôi",
      "firstName": "Tên",
      "lastName": "Họ",
      "email": "Email",
      "role": "Vai trò",
      "selectLanguage": "Chọn ngôn ngữ",
      "welcomeTitle": "Chào mừng đến với Eduhub",
      "welcomeDesc": "Nâng cao kỹ năng học tập của bạn. Truy cập bài tập về nhà, tài liệu nghiên cứu và phản hồi của giáo viên ở cùng một nơi.",
      "learnmore": "Tìm hiểu thêm",
      "allsubjcts": "Tất cả các môn học",
      "searchsubjects": "Tìm kiếm môn học...",
      "seeMore": "Xem thêm",
      "seeLess": "Thu gọn",
      "math": "Toán học",
      "science": "Khoa học",
      "history": "Lịch sử",
      "english": "Tiếng Anh",
      "geography": "Địa lý",
      "physics": "Vật lý",
      "chemistry": "Hóa học",
      "biology": "Sinh học",
      "art": "Nghệ thuật",
      "music": "Âm nhạc",
      "tech": "Công nghệ",
      "sports": "Thể thao",
      "loading": "Đang tải...",
      "hubSubtitle": "Trung tâm cho Học sinh & Giáo viên",
      "scholarshipOpportunities": "Cơ hội học bổng",
      "learningProgress": "Tiến độ học tập",
      "latestNews": "Tin tức giáo dục mới nhất",
      "Total Course Completion": "Tổng hoàn thành khóa học",
      "seemore": "Xem thêm",
      "seeless": "Thu gọn",
      "lessons": "Bài học",
      "Time": "Thời gian",
      "Others": "Khác",
      "schrolarshipOpportunities": "Cơ hội học bổng",
      "news&event": "Tin tức & Sự kiện",
      "LatesteducationNews": "Tin tức giáo dục mới nhất",
      "accountDetails": "Chi tiết tài khoản",
      "preferences": "Sở thích",
      "Dark Mode": "Chế độ tối",
      "Sign Out": "Đăng xuất",
    }
  };

  static String text(String language, String key) {
    return _texts[language]?[key] ?? key;
  }
}