class Localization {
  static final Map<String, Map<String, String>> _texts = {
    "English": {
      "home": "Home",
      "course": "Course",
      "class": "Class",
      "assignments": "Assignments",
      "profile": "Profile",
      "homeScreenTeacher": "Home Screen (Teacher)",
      "homeScreenStudent": "Home Screen (Student)",
      "coursePage": "Hello from course",
      "classesTeacher": "My Classes",
      "classesStudent": "Enrolled Classes",
      "assignmentsTeacher": "Assignments to Grade",
      "assignmentsStudent": "My Assignments",
      "firstName": "First Name",
      "lastName": "Last Name",
      "email": "Email",
      "role": "Role",
      "selectLanguage": "Select Language",
      "welcomeTitle": "Welcome to Eduhub",
      "welcomeDesc": "Boost your learning skills. Access homework, research materials, and teacher feedback all in one place.",
      "learnmore": "Learn More",
      "allsubjcts": "All Subjects",
      "searchsubjects": "Search subjects...",
    },
    "Khmer": {
      "home": "ផ្ទះ",
      "course": "វគ្គសិក្សា",
      "class": "ថ្នាក់",
      "assignments": "ការងារផ្ញើ",
      "profile": "ប្រវត្តិរូប",
      "homeScreenTeacher": "ផ្ទះ (គ្រូ)",
      "homeScreenStudent": "ផ្ទះ (សិស្ស)",
      "coursePage": "សួស្ដីពីវគ្គសិក្សា",
      "classesTeacher": "ថ្នាក់របស់ខ្ញុំ",
      "classesStudent": "ថ្នាក់ដែលចុះឈ្មោះ",
      "assignmentsTeacher": "ការងារដើម្បីផ្ដល់ពិន្ទុ",
      "assignmentsStudent": "ការងាររបស់ខ្ញុំ",
      "firstName": "នាមខ្លួន",
      "lastName": "នាមត្រកូល",
      "email": "អ៊ីម៉ែល",
      "role": "តួនាទី",
      "selectLanguage": "ជ្រើសភាសា",
      "welcomeTitle": "សូមស្វាគមន៍មកកាន់ Eduhub",
      "welcomeDesc": "បង្កើនជំនាញសិក្សារបស់អ្នក។ ចូលប្រើកិច្ចការផ្ទះ សម្ភារៈស្រាវជ្រាវ និងមតិកែលម្អរបស់គ្រូនៅកន្លែងតែមួយ។",
      "learnmore": "ស្វែងយល់បន្ថែម",
      "allsubjcts": "មុខវិជ្ជាទាំងអស់",
      "searchsubjects": "ស្វែងរកមុខវិជ្ជា...",
    },
    "Chinese": {
      "home": "主页",
      "course": "课程",
      "class": "班级",
      "assignments": "作业",
      "profile": "个人资料",
      "homeScreenTeacher": "主页（教师）",
      "homeScreenStudent": "主页（学生）",
      "coursePage": "你好，来自课程页面",
      "classesTeacher": "我的课程",
      "classesStudent": "已注册课程",
      "assignmentsTeacher": "待批作业",
      "assignmentsStudent": "我的作业",
      "firstName": "名字",
      "lastName": "姓氏",
      "email": "电子邮件",
      "role": "角色",
      "selectLanguage": "选择语言",
      "welcomeTitle": "欢迎来到 Eduhub",
      "welcomeDesc": "提升您的学习技能。在一个地方访问作业、研究材料和教师反馈。",
      "learnmore": "了解更多",
      "allsubjcts": "所有科目",
      "searchsubjects": "搜索科目...",
    },
    "Vietnamese": {
      "home": "Trang chủ",
      "course": "Khóa học",
      "class": "Lớp học",
      "assignments": "Bài tập",
      "profile": "Hồ sơ",
      "homeScreenTeacher": "Trang chủ (Giáo viên)",
      "homeScreenStudent": "Trang chủ (Học sinh)",
      "coursePage": "Xin chào từ trang khóa học",
      "classesTeacher": "Lớp của tôi",
      "classesStudent": "Lớp đã đăng ký",
      "assignmentsTeacher": "Bài tập cần chấm",
      "assignmentsStudent": "Bài tập của tôi",
      "firstName": "Tên",
      "lastName": "Họ",
      "email": "Email",
      "role": "Vai trò",
      "selectLanguage": "Chọn ngôn ngữ",
      "welcomeTitle": "Chào mừng đến với Eduhub",
      "welcomeDesc": "Nâng cao kỹ năng học tập của bạn. Truy cập bài tập về nhà, tài liệu nghiên cứu và phản hồi của giáo viên ở cùng một nơi.",
      "learnmore": "Tìm hiểu thêm",
      "allsubjcts": "Tất cả các môn học.",
      "searchsubjects": "Tìm kiếm môn học...",
    }
  };

  static String text(String language, String key) {
    return _texts[language]?[key] ?? key;
  }
}